name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
    - 'main'

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: strava-calendar-summary-web-service
  GCE_INSTANCE_ZONE: us-central1-a
  IMAGE_NAME: strava-calendar-summary-web-service-image

jobs:
  setup-build-publish-deploy:
    name: Build, Publish, and Deploy to Google Compute Engine
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Decrypt Secrets'
      run: sh ./.github/scripts/decrypt_secret.sh
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - run: |-
        gcloud --quiet auth configure-docker
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build
      run: |-
        docker build --tag "us-central1-docker.pkg.dev/$PROJECT_ID/strava-calendar-summary-web-service-container/$IMAGE_NAME:$GITHUB_SHA" .

    - name: Publish
      run: |-
        docker push "us-central1-docker.pkg.dev/$PROJECT_ID/strava-calendar-summary-web-service-container/$IMAGE_NAME:$GITHUB_SHA"
        
    - name: Deploy
      run: |-
        gcloud compute instances update-container "$GCE_INSTANCE" \
          --zone "$GCE_INSTANCE_ZONE" \
          --container-image "us-central1-docker.pkg.dev/$PROJECT_ID/strava-calendar-summary-web-service-container/$IMAGE_NAME:$GITHUB_SHA" \
          --container-env "STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }}" \
          --container-env "STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}" \
          --container-env "STRAVA_WEBHOOK_VERIFICATION_TOKEN=${{ secrets.STRAVA_WEBHOOK_VERIFICATION_TOKEN }}" \
          --container-env "STRAVA_SUBSCRIPTION_ID=${{ secrets.STRAVA_SUBSCRIPTION_ID }}" \
          --container-env "GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}" \
          --container-env "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" \
          --container-env "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          --container-env "COOKIE_SECRET_KEY=${{ secrets.COOKIE_SECRET_KEY }}" \
          --container-env "UI_BASE_URL=${{ secrets.UI_BASE_URL }}"